[[redirects]]
  from = "/api/*"
  to = "http://3.39.6.242:8080/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/image-proxy/images/*"
  to = "http://3.39.6.242:8080/images/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200